import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.features': 'Caractéristiques',
    'nav.howItWorks': 'Comment ça marche',
    'nav.testimonials': 'Témoignages',
    'nav.login': 'Connexion',
    'nav.signup': 'S\'inscrire',
    'nav.signupParent': 'Inscription Parent',
    'nav.signupTeacher': 'Inscription Enseignant',
    'nav.parentDesc': 'Pour l\'apprentissage à domicile',
    'nav.teacherDesc': 'Pour les éducateurs',
    'nav.dashboard': 'Tableau de bord',
    'nav.logout': 'Déconnexion',

    // Hero
    'hero.tag': 'Apprentissage moderne pour les futurs leaders',
    'hero.title': 'Apprentissage Amusant & Interactif pour les Enfants',
    'hero.titleLine1': 'Amusant & Interactif',
    'hero.titleLine2': 'Apprentissage pour les Enfants',
    'hero.desc': 'Bloom Buddies Academy combine un programme de classe mondiale avec des expériences ludiques pour faire de l\'apprentissage le moment fort de la journée de votre enfant.',
    'hero.startTrial': 'Essai Gratuit',
    'hero.watchDemo': 'Voir la démo',
    'hero.trusted': 'Approuvé par plus de 5 000 parents heureux',
    'hero.nextClass': 'Prochain cours : La magie des maths',
    'hero.startingIn': 'Commence dans 15 minutes',

    // Features
    'features.title': 'Pourquoi les familles nous aiment',
    'features.desc': 'Nous avons réimaginé l\'éducation en ligne pour qu\'elle soit engageante, efficace et sans effort pour les parents.',
    'feat.interactive.title': 'Cours Interactifs',
    'feat.interactive.desc': 'Engagement en temps réel avec des outils ludiques qui maintiennent les enfants concentrés et enthousiastes.',
    'feat.teachers.title': 'Enseignants Experts',
    'feat.teachers.desc': 'Des éducateurs agréés spécialisés dans la simplification de sujets complexes de manière agréable.',
    'feat.flexible.title': 'Horaires Flexibles',
    'feat.flexible.desc': 'Des cours qui s\'adaptent au style de vie de votre famille. Réservez ou reportez en un clic.',
    'feat.tracking.title': 'Suivi des Progrès',
    'feat.tracking.desc': 'Rapports détaillés et perspectives pour vous aider à célébrer chaque étape franchie par votre enfant.',

    // How It Works
    'how.title': 'Des étapes simples vers le succès',
    'how.desc': 'Rejoindre Bloom Buddies Academy est un jeu d\'enfant. Voici comment commencer dès aujourd\'hui.',
    'step.1.title': 'S\'inscrire',
    'step.1.desc': 'Parlez-nous des intérêts de votre enfant et de votre emploi du temps préféré.',
    'step.2.title': 'Choisir un essai',
    'step.2.desc': 'Choisissez un cours d\'essai gratuit parmi plus de 200 sujets.',
    'step.3.title': 'Commencer à apprendre',
    'step.3.desc': 'Rejoignez le plaisir et regardez la confiance de votre enfant s\'épanouir dans notre classe en direct.',

    // Testimonials
    'test.title': 'Recommandé par des parents comme vous',
    'test.subtitle': 'Rejoignez des milliers de familles qui grandissent déjà avec Bloom.',
    'test.rating': 'Note de 4.9/5',
    'test.independent': 'Avis indépendants',

    // CTA
    'cta.title': 'Réservez un cours d\'essai gratuit',
    'cta.desc': 'Aucune carte de crédit requise. Découvrez pourquoi Bloom Buddies Academy est le premier choix pour les familles innovantes.',
    'cta.button': 'Réclamez votre créneau gratuit',

    // Footer
    'footer.desc': 'Donner aux enfants les moyens d\'atteindre leur plein potentiel grâce à une éducation moderne, amusante et interactive.',
    'footer.newsletter': 'Rejoignez notre newsletter',
    'footer.newsletterDesc': 'Recevez les dernières mises à jour et conseils éducatifs directement dans votre boîte de réception.',
    'footer.rights': '© 2026 Bloom Buddies Academy Inc. Tous droits réservés.',
    'auth.availability': 'Disponibilité',
    'auth.yourProfile': 'Votre profil',
    'auth.continueToAvailability': 'Continuer vers la disponibilité',
    'auth.resetPassword': 'Réinitialiser le mot de passe',
    'auth.sendResetLink': 'Envoyer le lien de réinitialisation',
    'auth.checkEmail': 'Vérifiez vos e-mails pour le lien de réinitialisation',
    'auth.invalidLink': 'Lien invalide',
    'auth.invalidLinkDesc': 'Le lien de réinitialisation est invalide ou a expiré.',
    'auth.updatePassword': 'Mettre à jour le mot de passe',
    'auth.passwordUpdated': 'Le mot de passe a été réinitialisé avec succès',
    'auth.backToLogin': 'Retour à la connexion',
    'auth.redirecting': 'Redirection vers la connexion...',
    'auth.forgotDesc': 'Entrez votre e-mail pour recevoir un lien de réinitialisation',
    'auth.errorUnexpected': 'Une erreur inattendue est survenue. Veuillez réessayer.',

    // AuthModal
    'auth.welcome': 'Bienvenue !',
    'auth.loginDesc': 'Connectez-vous à votre tableau de bord pour continuer à apprendre',
    'auth.email': 'Adresse e-mail',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.forgot': 'Mot de passe oublié ?',
    'auth.noAccount': 'Vous n\'avez pas encore de compte ?',
    'auth.loading': 'Chargement...',
    'auth.login': 'Se connecter',
    'auth.parentReg': 'Inscription Parent',
    'auth.teacherReg': 'Inscription Enseignant',
    'auth.teacherOnboarding': 'Intégration des Enseignants',
    'auth.teacherOnboardingDesc': 'Partagez votre expertise avec la prochaine génération',
    'auth.profilePhoto': 'Photo de profil',
    'auth.teacherDob': 'Date de naissance',
    'auth.selectTimezone': 'Sélectionnez le fuseau horaire',
    'auth.aboutMeMin': 'Minimum 250 caractères nécessaires pour instaurer la confiance',
    'auth.teacherStep2': 'Étape 2 : Définissez vos heures d\'enseignement',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.telephone': 'Téléphone',
    'auth.city': 'Ville',
    'auth.numChildren': 'Nombre d\'enfants',
    'auth.childDob': 'Date de naissance de l\'enfant',
    'auth.learningWindow': 'Fenêtre d\'apprentissage',
    'auth.scheduleDesc': 'Définissez la fenêtre d\'apprentissage idéale pour vos enfants.',
    'auth.addSlot': 'Ajouter créneau',
    'auth.createParent': 'Créer un compte parent',
    'auth.createTeacher': 'Créer un compte enseignant',
    'auth.alreadyAccount': 'Déjà inscrit ?',
    'auth.loginNow': 'Connectez-vous maintenant',
    'auth.timezone': 'Fuseau horaire',
    'auth.aboutMe': 'À propos de moi',
    'auth.aboutMePlaceholder': 'Partagez votre philosophie d\'enseignement...',
    'auth.minChars': 'Minimum 250 caractères nécessaires pour instaurer la confiance',
    'auth.weeklyAvailability': 'Disponibilité hebdomadaire',
    'auth.syncHours': 'Synchronisez vos heures d\'enseignement',
    'auth.clearSelection': 'Effacer la sélection',
    'auth.slotsSelected': 'créneaux sélectionnés',

    // Dashboard
    'dash.welcome': 'Bon retour,',
    'dash.today': 'Voici ce qui se passe aujourd\'hui',
    'dash.classes': 'Cours',
    'dash.joinClass': 'Rejoindre le cours maintenant',
    'dash.currentSession': 'Session actuelle',
    'dash.creativeWriting': 'Écritue Créative Interactive',

    // Days
    'days.Monday': 'Lundi',
    'days.Tuesday': 'Mardi',
    'days.Wednesday': 'Mercredi',
    'days.Thursday': 'Jeudi',
    'days.Friday': 'Vendredi',
    'days.Saturday': 'Samedi',
    'days.Sunday': 'Dimanche',

    // Menage Page
    'nav.menage': 'Ménage',
    'menage.hero.badge': 'SAP 993001130',
    'menage.hero.title': 'Bienvenue à votre domicile propre',
    'menage.hero.subtext': 'Votre partenaire de confiance pour un domicile impeccable et serein',
    'menage.hero.cta': 'Je réserve',
    'menage.services.title': 'Nos services',
    'menage.services.subtitle': 'Nettoyage, repassage, vitres et grand ménage.',
    'menage.service1.title': 'Nettoyage courant',
    'menage.service1.desc': 'Entretien régulier pour garder votre maison impeccable.',
    'menage.service2.title': 'Repassage',
    'menage.service2.desc': 'Finition soignée de votre linge pour un rendu parfait.',
    'menage.service3.title': 'Grand ménage',
    'menage.service3.desc': 'Nettoyage en profondeur, idéal pour le printemps.',
    'menage.testimonials.name1': 'Marie L.',
    'menage.testimonials.quote1': 'Service impeccable, personnel toujours ponctuel et très professionnel.',
    'menage.testimonials.name2': 'Paul D.',
    'menage.testimonials.quote2': 'Grâce à eux, ma maison est toujours impeccable sans stress.',
    'menage.cta.title': 'Réservez maintenant',
    'menage.cta.subtext': 'Planifiez votre ménage en toute simplicité avec Bloom Buddies Academy.',
    'menage.cta.button': 'Je réserve',
    'menage.cta.note': "Avance immédiate de crédit d'impôt disponible",
    'menage.faq.title': 'Questions fréquentes',
    'menage.faq.q1': "Qu'est ce que l'avance immédiate ?",
    'menage.faq.a1': 'Un service gratuit pour simplifier votre crédit d\'impôt.',
    'menage.faq.q2': "Comment m'inscrire ?",
    'menage.faq.a2': "Nous gérons l'inscription pour vous, simple et rapide.",
    'menage.faq.q3': 'Quels services proposez-vous ?',
    'menage.faq.a3': 'Nous proposons ménage courant, repassage, nettoyage de vitres et grand ménage de printemps.',
    'menage.faq.q4': 'Comment fonctionne le paiement ?',
    'menage.faq.a4': 'Le client active son compte, puis la validation des paiements prend 48h.',
    'menage.faq.q5': "Qui est l'employeur ?",
    'menage.faq.a5': 'Nous sommes l\'employeur, vous bénéficiez d\'un suivi qualité constant.',
    'menage.footer.address': '7 rue Meyerbeer 75009 Paris, France. Lundi–Vendredi, 9h–18h',
    'menage.footer.cities': 'Paris • Lyon • Toulouse • Nice • Nantes • Marseille • Montpellier • Strasbourg • Bordeaux • Lille',
    'menage.footer.copyright': '© Bloom Buddies Academy. Fourni par Enqavon service.',

    // Additional Auth
    'auth.loginSuccess': 'Connexion réussie ! Redirection...',
    'auth.loginFailed': 'Échec de la connexion',
    'auth.failedResetLink': 'Échec de l\'envoi du lien de réinitialisation',
    'auth.passwordMin': 'Le mot de passe doit comporter au moins 6 caractères',
    'auth.passwordMatch': 'Les mots de passe ne correspondent pas',
    'auth.failedReset': 'Échec de la réinitialisation du mot de passe',
    'auth.newSecurePassword': 'Créez un nouveau mot de passe sécurisé',

    // Classroom
    'class.cameraOff': 'Caméra désactivée',
    'class.preMeetingCheck': 'Vérification avant le cours',
    'class.readyToBloom': 'Prêt à s\'épanouir ?',
    'class.checkEquipment': 'Vérifiez votre équipement avant de rejoindre',
    'class.checkEquipmentTeacher': 'Configurez votre équipement pour enseigner',
    'class.checkEquipmentStudent': 'Vérifiez votre équipement pour apprendre',
    'class.muted': 'Muet',
    'class.voiceActive': 'Voix active',
    'class.joinClass': 'Rejoindre le cours',
    'class.leaveTerminal': 'Quitter le terminal',
    'class.metaClass': 'Méta Classe',
    'class.chat': 'Chat',
    'class.whiteboard': 'Tableau blanc',
    'class.resources': 'Ressources',
    'class.hideBoards': 'Masquer les tableaux',
    'class.endClass': 'Finir le cours',
    'class.classroomContent': 'Zone de contenu de la classe',
    'class.waitingTeacher': 'En attente de l\'enseignant',
    'class.waitingStudent': 'En attente de l\'élève',
    'class.student': 'Élève',
    'class.teacher': 'Enseignant',
    'class.settingUpWhiteboard': 'Configuration du tableau blanc',
    'class.setupFailed': 'Échec de la configuration',
    'class.whiteboardNotReady': 'Tableau blanc non prêt',
    'class.manageClass': 'Gérer le cours',
    'class.child': 'Enfant',
    'class.studentSession': 'Session de l\'élève',
    'class.onlyImagesPDF': 'Seuls les images et les PDF sont autorisés.',

    // Whiteboard
    'wb.initializing': 'Initialisation du tableau blanc',
    'wb.downloading': 'Téléchargement du matériel',
    'wb.loading': 'Chargement du matériel',
    'wb.preparing': 'Préparation de votre canevas magique pour une session productive...',
    'wb.retrieving': 'Récupération du livre partagé depuis la bibliothèque cloud...',
    'wb.rendering': 'Rendu du matériel partagé sur tous les appareils...',
    'wb.retryConnection': 'Réessayer la connexion',
    'wb.failedLoadPdf': 'Échec du chargement du PDF',
    'wb.zoomIn': 'Zoom avant',
    'wb.zoomOut': 'Zoom arrière',
    'wb.page': 'Page',
    'wb.select': 'Sélectionner',
    'wb.pencil': 'Crayon',
    'wb.highlight': 'Surligneur',
    'wb.laser': 'Pointeur laser',
    'wb.eraser': 'Gomme',
    'wb.rectangle': 'Rectangle',
    'wb.ellipse': 'Ellipse',
    'wb.text': 'Texte',
    'wb.clear': 'Effacer ?',
    'wb.yes': 'Oui',
    'wb.no': 'Non',
    'wb.stopSharing': 'Arrêter le partage',
    'wb.shareScreen': 'Partager l\'écran',
    'wb.pdfResources': 'Ressources PDF',
    'wb.hideBoard': 'Masquer le tableau',
    'wb.clearAnnotations': 'Effacer les annotations de cette page',
    'wb.lockAnnotations': 'Verrouiller les annotations des élèves',
    'wb.unlockAnnotations': 'Déverrouiller les annotations des élèves',
    'wb.connecting': 'Connexion...',
    'wb.downloadingPercent': 'Téléchargement',
    'wb.renderingPercent': 'Rendu...',

    // Material Manager
    'mat.lessonMaterials': 'Matériel de cours',
    'mat.uploadShare': 'Télécharger & Partager des PDF',
    'mat.loadingMaterials': 'Chargement du matériel...',
    'mat.noMaterials': 'Aucun matériel n\'a encore été téléchargé. Téléchargez un PDF pour commencer à le partager.',
    'mat.shareLive': 'Partager en direct',
    'mat.stopSharing': 'Arrêter le partage',
    'mat.activelySharing': 'Partage actif',
    'mat.uploadNew': 'Télécharger un nouveau matériel',
    'mat.uploading': 'Téléchargement',
    'mat.onlyPDF': 'Seuls les fichiers PDF sont autorisés.',
    'mat.loadFailed': 'Échec du chargement du matériel de cours.',
    'class.academy': 'Academy',
    'class.contentAreaTeacher': 'Cliquez sur \'Tableau blanc\' ou \'Ressources\' pour commencer à partager des supports avec votre élève.',
    'class.contentAreaStudent': 'En attente que le professeur partage des supports pédagogiques ou active le tableau blanc...',
    'class.waitingForTeacher': 'En attente du professeur',
    'class.waitingForStudent': 'En attente de l\'élève',
    'footer.ourCities': 'Nos Villes',
    'hero.fun': '100% Fun',
    'hero.courses': 'Cours',
    'nav.academy': 'Academy',
    'chat.readyToSend': 'Prêt à envoyer',
    'chat.uploading': 'Téléchargement du fichier...',
    'chat.placeholder': 'Tapez un message...',
    'dash.fetching': 'Récupération de vos sessions...',
    'badge.reward': 'Récompenser',
    'badge.youGave': 'Vous avez donné un badge à',
    'badge.teacherGave': 'Votre enseignant vous a donné un badge',
    'class.sharingScreen': 'Partage d\'écran',
    'class.me': 'Moi',
    'class.user': 'Utilisateur',
    'badge.rewardTitle': 'Récompenser l\'élève',
    'class.leaveClass': 'Quitter la classe',
    'class.endClassTitle': 'Mettre fin au cours pour tout le monde',
    'material.failedLoad': 'Échec du chargement du matériel de cours.',
    'material.uploadFailed': 'Échec du téléchargement. Veuillez réessayer.',
    'material.errorDuringUpload': 'Une erreur s\'est produite lors du téléchargement.',
    'material.lessonMaterials': 'Matériel de cours',
    'material.uploadShare': 'Télécharger et partager des PDF',
    'material.loading': 'Chargement du matériel...',
    'material.noMaterials': 'Aucun matériel n\'a encore été téléchargé. Téléchargez un PDF pour commencer à le partager avec vos élèves.',
    'material.stopSharing': 'Arrêter le partage',
    'material.shareLive': 'Partager en direct',
    'material.activelySharing': 'Partage actif',
    'material.uploading': 'Téléchargement',
    'material.uploadNew': 'Télécharger un nouveau matériel',
    'whiteboard.failedDownload': 'Échec du téléchargement du matériel. Veuillez réessayer.',
    'whiteboard.networkError': 'Une erreur réseau s\'est produite lors de la récupération du matériel.',
    'whiteboard.failedJoin': 'Échec de la connexion au tableau blanc',
    'whiteboard.initializing': 'Initialisation du tableau blanc',
    'whiteboard.downloadingMaterial': 'Téléchargement du matériel',
    'whiteboard.loadingMaterial': 'Chargement du matériel',
    'whiteboard.preparingCanvas': 'Préparation de votre canevas magique pour une séance productive...',
    'whiteboard.retrievingBook': 'Récupération du livre partagé depuis la bibliothèque cloud...',
    'whiteboard.renderingMaterial': 'Rendu du matériel partagé sur tous les appareils magiques...',
    'whiteboard.connecting': 'Connexion...',
    'whiteboard.downloading': 'Téléchargement',
    'whiteboard.rendering': 'Rendu...',
    'whiteboard.retryConnection': 'Réessayer la connexion',
    'whiteboard.page': 'Page',
    'whiteboard.clearQuestion': 'Effacer ?',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.brandName': 'Bloom Buddies Academy',
    'auth.childrenSchedule': 'Calendrier des enfants',
    'days.monday': 'Lundi',
    'days.tuesday': 'Mardi',
    'days.wednesday': 'Mercredi',
    'days.thursday': 'Jeudi',
    'days.friday': 'Vendredi',
    'days.saturday': 'Samedi',
    'days.sunday': 'Dimanche',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.howItWorks': 'How it Works',
    'nav.testimonials': 'Success Stories',
    'nav.login': 'Log In',
    'nav.signup': 'Sign Up',
    'nav.signupParent': 'Parent Signup',
    'nav.signupTeacher': 'Teacher Signup',
    'nav.parentDesc': 'For home learning',
    'nav.teacherDesc': 'For educators',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',

    // Hero
    'hero.tag': 'Modern Learning for Next-Gen Leaders',
    'hero.title': 'Fun & Interactive Learning for Kids',
    'hero.titleLine1': 'Fun & Interactive',
    'hero.titleLine2': 'Learning for Kids',
    'hero.desc': 'Bloom Buddies Academy combines world-class curriculum with gamified experiences to make learning the highlight of your child\'s day.',
    'hero.startTrial': 'Start Free Trial',
    'hero.watchDemo': 'Watch Class Demo',
    'hero.trusted': 'Trusted by 5,000+ happy parents',
    'hero.nextClass': 'Next Class: Magic of Math',
    'hero.startingIn': 'Starting in 15 minutes',

    // Features
    'features.title': 'Why families love us',
    'features.desc': 'We\'ve reimagined online education from the ground up to be engaging, effective, and effortless for parents.',
    'feat.interactive.title': 'Interactive Classes',
    'feat.interactive.desc': 'Real-time engagement with gamified tools that keep kids focused and excited.',
    'feat.teachers.title': 'Expert Teachers',
    'feat.teachers.desc': 'Vetted educators who specialize in making complex subjects simple and delightful.',
    'feat.flexible.title': 'Flexible Scheduling',
    'feat.flexible.desc': 'Classes that fit your family\'s busy lifestyle. Book or reschedule with one click.',
    'feat.tracking.title': 'Progress Tracking',
    'feat.tracking.desc': 'Detailed reports and insights to help you celebrate every milestone your child hits.',

    // How It Works
    'how.title': 'Simple Steps to Success',
    'how.desc': 'Joining Bloom Buddies Academy is as easy as pie. Here\'s how to get started today.',
    'step.1.title': 'Sign Up',
    'step.1.desc': 'Tell us about your child\'s interests and your preferred schedule.',
    'step.2.title': 'Select Trial',
    'step.2.desc': 'Pick a free trial class that fits your schedule from our 200+ topics.',
    'step.3.title': 'Start Learning',
    'step.3.desc': 'Join the fun and watch your child\'s confidence bloom in our live classroom.',

    // Testimonials
    'test.title': 'Recommended by parents like you',
    'test.subtitle': 'Join thousands of families already growing with Bloom.',
    'test.rating': '4.9/5 Rating',
    'test.independent': 'Independent Reviews',

    // CTA
    'cta.title': 'Book a Free Trial Class',
    'cta.desc': 'No credit card required. Experience why Bloom Buddies Academy is the top choice for innovative families.',
    'cta.button': 'Claim Your Free Slot',

    // Footer
    'footer.desc': 'Empowering children to reach their full potential through modern, fun, and interactive education.',
    'footer.newsletter': 'Join our newsletter',
    'footer.newsletterDesc': 'Get the latest updates and educational tips directly in your inbox.',
    'footer.rights': '© 2026 Bloom Buddies Academy Inc. All rights reserved.',
    'auth.availability': 'Availability', 
    'auth.yourProfile': 'Your Profile', 
    'auth.continueToAvailability': 'Continue to Availability',
    'auth.resetPassword': 'Reset Password',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.checkEmail': 'Check your email for reset link',
    'auth.invalidLink': 'Invalid Link',
    'auth.invalidLinkDesc': 'The reset password link is invalid or has expired.',
    'auth.updatePassword': 'Update Password',
    'auth.passwordUpdated': 'Password has been reset successfully',
    'auth.backToLogin': 'Back to Login',
    'auth.redirecting': 'Redirecting to login...',
    'auth.forgotDesc': 'Enter your email to receive a password reset link',
    'auth.errorUnexpected': 'An unexpected error occurred. Please try again.',

    // AuthModal
    'auth.welcome': 'Welcome back!',
    'auth.loginDesc': 'Log in to your dashboard to continue learning',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgot': 'Forgot password?',
    'auth.noAccount': 'Don\'t have an account yet?',
    'auth.loading': 'Loading...',
    'auth.login': 'Log In',
    'auth.parentReg': 'Parent Registration',
    'auth.teacherReg': 'Teacher Onboarding',
    'auth.teacherOnboarding': 'Teacher Onboarding',
    'auth.teacherOnboardingDesc': 'Share your expertise with the next generation',
    'auth.profilePhoto': 'Profile Photo',
    'auth.teacherDob': 'Date of Birth',
    'auth.selectTimezone': 'Select Timezone',
    'auth.aboutMeMin': 'Minimum 250 characters needed to build trust',
    'auth.teacherStep2': 'Step 2: Define your teaching hours',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.telephone': 'Telephone',
    'auth.city': 'City',
    'auth.numChildren': 'Number of Children',
    'auth.childDob': 'Child Date of Birth',
    'auth.learningWindow': 'Learning Window',
    'auth.scheduleDesc': 'Select preferred time windows for online classes',
    'auth.addSlot': 'Add Slot',
    'auth.createParent': 'Create Parent Account',
    'auth.createTeacher': 'Create Teacher Account',
    'auth.alreadyAccount': 'Already signed up?',
    'auth.loginNow': 'Login now',
    'auth.timezone': 'Timezone',
    'auth.aboutMe': 'About Me',
    'auth.aboutMePlaceholder': 'Share your teaching philosophy...',
    'auth.minChars': 'Minimum 250 characters needed to build trust',
    'auth.weeklyAvailability': 'Weekly Availability',
    'auth.syncHours': 'Sync your teaching hours',
    'auth.clearSelection': 'Clear Selection',
    'auth.slotsSelected': 'slots selected',

    // Dashboard
    'dash.welcome': 'Welcome back,',
    'dash.today': 'Here\'s what\'s happening today',
    'dash.classes': 'Classes',
    'dash.joinClass': 'Join Live Class Now',
    'dash.currentSession': 'Current Session',
    'dash.creativeWriting': 'Interactive Creative Writing',

    // Days
    'days.Monday': 'Monday',
    'days.Tuesday': 'Tuesday',
    'days.Wednesday': 'Wednesday',
    'days.Thursday': 'Thursday',
    'days.Friday': 'Friday',
    'days.Saturday': 'Saturday',
    'days.Sunday': 'Sunday',

    // Menage Page
    'nav.menage': 'Cleaning',
    'menage.hero.badge': 'SAP 993001130',
    'menage.hero.title': 'Welcome to your clean home',
    'menage.hero.subtext': 'Your trusted partner for an impeccable and serene home',
    'menage.hero.cta': 'Book now',
    'menage.services.title': 'Our Services',
    'menage.services.subtitle': 'Cleaning, ironing, windows and deep cleaning.',
    'menage.service1.title': 'Regular Cleaning',
    'menage.service1.desc': 'Regular maintenance to keep your home impeccable.',
    'menage.service2.title': 'Ironing',
    'menage.service2.desc': 'Careful finish of your laundry for a perfect result.',
    'menage.service3.title': 'Deep Cleaning',
    'menage.service3.desc': 'Deep cleaning, ideal for spring.',
    'menage.testimonials.name1': 'Marie L.',
    'menage.testimonials.quote1': 'Impeccable service, staff always punctual and very professional.',
    'menage.testimonials.name2': 'Paul D.',
    'menage.testimonials.quote2': 'Thanks to them, my house is always impeccable without stress.',
    'menage.cta.title': 'Book Now',
    'menage.cta.subtext': 'Plan your cleaning easily with Bloom Buddies Academy.',
    'menage.cta.button': 'Book now',
    'menage.cta.note': "Immediate tax credit advance available",
    'menage.faq.title': 'Frequent Questions',
    'menage.faq.q1': "What is the immediate advance?",
    'menage.faq.a1': 'A free service to simplify your tax credit.',
    'menage.faq.q2': "How to register?",
    'menage.faq.a2': "We handle the registration for you, simple and fast.",
    'menage.faq.q3': 'What services do you offer?',
    'menage.faq.a3': 'We offer regular cleaning, ironing, window cleaning and deep spring cleaning.',
    'menage.faq.q4': 'How does payment work?',
    'menage.faq.a4': 'The client activates their account, then payment validation takes 48h.',
    'menage.faq.q5': "Who is the employer?",
    'menage.faq.a5': 'We are the employer, you benefit from constant quality monitoring.',
    'menage.footer.address': '7 rue Meyerbeer 75009 Paris, France. Monday–Friday, 9am–6pm',
    'menage.footer.cities': 'Paris • Lyon • Toulouse • Nice • Nantes • Marseille • Montpellier • Strasbourg • Bordeaux • Lille',
    'menage.footer.copyright': '© Bloom Buddies Academy. Provided by Enqavon service.',

    // Additional Auth
    'auth.loginSuccess': 'Login successful! Redirecting...',
    'auth.loginFailed': 'Login failed',
    'auth.failedResetLink': 'Failed to send reset link',
    'auth.passwordMin': 'Password must be at least 6 characters',
    'auth.passwordMatch': 'Passwords do not match',
    'auth.failedReset': 'Failed to reset password',
    'auth.newSecurePassword': 'Create a new secure password',

    // Classroom
    'class.cameraOff': 'Camera is Off',
    'class.preMeetingCheck': 'Pre-Meeting Check',
    'class.readyToBloom': 'Ready to Bloom?',
    'class.checkEquipment': 'Check your equipment before joining',
    'class.checkEquipmentTeacher': 'Set up your teaching equipment',
    'class.checkEquipmentStudent': 'Check your equipment for learning',
    'class.muted': 'Muted',
    'class.voiceActive': 'Voice Active',
    'class.joinClass': 'Join Class',
    'class.leaveTerminal': 'Leave Terminal',
    'class.metaClass': 'Meta Class',
    'class.chat': 'Chat',
    'class.whiteboard': 'Whiteboard',
    'class.resources': 'Resources',
    'class.hideBoards': 'Hide Boards',
    'class.endClass': 'End Class',
    'class.classroomContent': 'Classroom Content Area',
    'class.waitingTeacher': 'Waiting for Teacher',
    'class.waitingStudent': 'Waiting for Student',
    'class.student': 'Student',
    'class.teacher': 'Teacher',
    'class.settingUpWhiteboard': 'Setting Up Whiteboard',
    'class.setupFailed': 'Setup Failed',
    'class.whiteboardNotReady': 'Whiteboard Not Ready',
    'class.manageClass': 'Manage Class',
    'class.child': 'Child',
    'class.studentSession': 'Session of the student',
    'class.onlyImagesPDF': 'Only images and PDFs are allowed.',

    // Whiteboard
    'wb.initializing': 'Initializing Whiteboard',
    'wb.downloading': 'Downloading Material',
    'wb.loading': 'Loading Material',
    'wb.preparing': 'Preparing your magical canvas for a productive session...',
    'wb.retrieving': 'Retrieving the shared book from the cloud library...',
    'wb.rendering': 'Rendering the shared material across all magical devices...',
    'wb.retryConnection': 'Retry Connection',
    'wb.failedLoadPdf': 'Failed to load PDF',
    'wb.zoomIn': 'Zoom In',
    'wb.zoomOut': 'Zoom Out',
    'wb.page': 'Page',
    'wb.select': 'Select',
    'wb.pencil': 'Pencil',
    'wb.highlight': 'Highlight',
    'wb.laser': 'Laser Pointer',
    'wb.eraser': 'Eraser',
    'wb.rectangle': 'Rectangle',
    'wb.ellipse': 'Ellipse',
    'wb.text': 'Text',
    'wb.clear': 'Clear?',
    'wb.yes': 'Yes',
    'wb.no': 'No',
    'wb.stopSharing': 'Stop Sharing',
    'wb.shareScreen': 'Share Screen',
    'wb.pdfResources': 'PDF Resources',
    'wb.hideBoard': 'Hide Board',
    'wb.clearAnnotations': 'Clear annotations on this page',
    'wb.lockAnnotations': 'Lock student annotations',
    'wb.unlockAnnotations': 'Unlock student annotations',
    'wb.connecting': 'Connecting...',
    'wb.downloadingPercent': 'Downloading',
    'wb.renderingPercent': 'Rendering...',

    // Material Manager
    'mat.lessonMaterials': 'Lesson Materials',
    'mat.uploadShare': 'Upload & Share PDFs',
    'mat.loadingMaterials': 'Loading Materials...',
    'mat.noMaterials': 'No materials uploaded yet. Upload a PDF to start sharing.',
    'mat.shareLive': 'Share Live',
    'mat.stopSharing': 'Stop Sharing',
    'mat.activelySharing': 'Actively Sharing',
    'mat.uploadNew': 'Upload New Material',
    'mat.uploading': 'Uploading',
    'mat.onlyPDF': 'Only PDF files are allowed.',
    'mat.loadFailed': 'Failed to load lesson materials.',
    'class.academy': 'Academy',
    'class.contentAreaTeacher': 'Click \'Whiteboard\' or \'Resources\' to start sharing materials with your student.',
    'class.contentAreaStudent': 'Waiting for the teacher to share learning materials or activate the whiteboard...',
    'class.waitingForTeacher': 'Waiting for Teacher',
    'class.waitingForStudent': 'Waiting for Student',
    'footer.ourCities': 'Our Cities',
    'hero.fun': '100% Fun',
    'hero.courses': 'Courses',
    'nav.academy': 'Academy',
    'chat.readyToSend': 'Ready to send',
    'chat.uploading': 'Uploading File...',
    'chat.placeholder': 'Type message...',
    'dash.fetching': 'Fetching your sessions...',
    'badge.reward': 'Reward',
    'badge.youGave': 'You gave a badge to',
    'badge.teacherGave': 'Your teacher gave you a badge',
    'class.sharingScreen': 'Sharing Screen',
    'class.me': 'Me',
    'class.user': 'User',
    'badge.rewardTitle': 'Reward Student',
    'class.leaveClass': 'Leave Class',
    'class.endClassTitle': 'End Class for Everyone',
    'material.failedLoad': 'Failed to load lesson materials.',
    'material.uploadFailed': 'Upload failed. Please try again.',
    'material.errorDuringUpload': 'An error occurred during upload.',
    'material.lessonMaterials': 'Lesson Materials',
    'material.uploadShare': 'Upload & Share PDFs',
    'material.loading': 'Loading Materials...',
    'material.noMaterials': 'No materials uploaded yet. Upload a PDF to start sharing with your students.',
    'material.stopSharing': 'Stop Sharing',
    'material.shareLive': 'Share Live',
    'material.activelySharing': 'Actively Sharing',
    'material.uploading': 'Uploading',
    'material.uploadNew': 'Upload New Material',
    'whiteboard.failedDownload': 'Failed to download material. Please try again.',
    'whiteboard.networkError': 'Network error occurred while fetching material.',
    'whiteboard.failedJoin': 'Failed to join whiteboard',
    'whiteboard.initializing': 'Initializing Whiteboard',
    'whiteboard.downloadingMaterial': 'Downloading Material',
    'whiteboard.loadingMaterial': 'Loading Material',
    'whiteboard.preparingCanvas': 'Preparing your magical canvas for a productive session...',
    'whiteboard.retrievingBook': 'Retrieving the shared book from the cloud library...',
    'whiteboard.renderingMaterial': 'Rendering the shared material across all magical devices...',
    'whiteboard.connecting': 'Connecting...',
    'whiteboard.downloading': 'Downloading',
    'whiteboard.rendering': 'Rendering...',
    'whiteboard.retryConnection': 'Retry Connection',
    'whiteboard.page': 'Page',
    'whiteboard.clearQuestion': 'Clear?',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.brandName': 'Bloom Buddies Academy',
    'auth.registrationSuccess': 'Registration successful!',
    'auth.registrationFailed': 'Registration failed',
    'auth.noSlots': 'No slots defined for this day.',
    'auth.start': 'Start',
    'auth.end': 'End',
    'auth.continueToSchedule': 'Continue to Schedule',
    'auth.backToDetails': 'Back to Details',
    'auth.available': 'Available',
    'auth.backToProfile': 'Back to Profile',
    'days.monday': 'Monday',
    'days.tuesday': 'Tuesday',
    'days.wednesday': 'Wednesday',
    'days.thursday': 'Thursday',
    'days.friday': 'Friday',
    'days.saturday': 'Saturday',
    'days.sunday': 'Sunday',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
